package com.visionstock.dto;

import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * DTO for creating a new Product.
 * The {@code id} is generated by the Frontend (Offline-First) and sent in the request.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProductCreateDTO {

    @NotNull(message = "ID is required (generated by the frontend)")
    private UUID id;

    private String referencia;

    @NotBlank(message = "Description is required")
    private String descricao;

    private String tamanho;

    private String cor;

    private String marca;

    private String codigoBarras;

    @Digits(integer = 8, fraction = 2, message = "Cost price must have up to 8 integer digits and 2 decimal places")
    @DecimalMin(value = "0.0", inclusive = true, message = "Cost price must be at least 0")
    @DecimalMax(value = "99999999.99", inclusive = true, message = "Cost price exceeds maximum allowed value")
    private BigDecimal precoCusto;

    @NotNull(message = "Sale price is required")
    @DecimalMin(value = "0.0", inclusive = true, message = "Sale price must be at least 0")
    @DecimalMax(value = "99999999.99", inclusive = true, message = "Sale price exceeds maximum allowed value")
    @Digits(integer = 8, fraction = 2, message = "Sale price must have up to 8 integer digits and 2 decimal places")
    private BigDecimal precoVenda;

    @NotNull(message = "Initial quantity is required")
    @Min(value = 0, message = "Initial quantity must be at least 0")
    private Integer quantidadeInicial;

    @Min(value = 0, message = "Minimum quantity must be at least 0")
    private Integer quantidadeMinima;
}
