package com.visionstock.dto;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * DTO for creating a new Product.
 * The {@code id} is generated by the Frontend (Offline-First) and sent in the request.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProductCreateDTO {

    @NotNull(message = "ID is required (generated by the frontend)")
    private UUID id;

    private String referencia;

    private String descricao;

    private String tamanho;

    private String cor;

    private String marca;

    private String codigoBarras;

    private BigDecimal precoCusto;

    private BigDecimal precoVenda;

    @NotNull(message = "Initial quantity is required")
    @Min(value = 0, message = "Initial quantity must be at least 0")
    private Integer quantidadeInicial;
}
